/**
 * Sample 8×8 binary rasters for known shapes.
 * Each raster is a flat 64-element array (row-major, top-to-bottom).
 * 1 = filled, 0 = empty.
 *
 * Visual key: '#' = 1, '.' = 0
 */

/** Helper: parse a visual grid string into a flat raster array */
export function parseGrid(visual: string): number[] {
  const rows = visual.trim().split('\n').map(r => r.trim());
  if (rows.length !== 8) throw new Error(`Expected 8 rows, got ${rows.length}`);
  const raster: number[] = [];
  for (const row of rows) {
    const cells = row.split('');
    if (cells.length !== 8) throw new Error(`Expected 8 cols, got ${cells.length} in "${row}"`);
    for (const c of cells) {
      raster.push(c === '#' ? 1 : 0);
    }
  }
  return raster;
}

// ─── Basic shapes ───────────────────────────────────────────────

/** 4×4 solid square centered */
export const SQUARE_4x4 = parseGrid(`
........
........
..####..
..####..
..####..
..####..
........
........
`);

/** Full 8×8 filled square */
export const SQUARE_FULL = parseGrid(`
########
########
########
########
########
########
########
########
`);

/** Single pixel in center */
export const SINGLE_PIXEL = parseGrid(`
........
........
........
...#....
........
........
........
........
`);

/** Horizontal line (1px tall) */
export const H_LINE = parseGrid(`
........
........
........
########
........
........
........
........
`);

/** Vertical line (1px tall) */
export const V_LINE = parseGrid(`
...#....
...#....
...#....
...#....
...#....
...#....
...#....
...#....
`);

// ─── Geometric shapes ───────────────────────────────────────────

/** Triangle pointing up */
export const TRIANGLE_UP = parseGrid(`
........
...##...
..####..
..####..
.######.
.######.
########
........
`);

/** L-shape */
export const L_SHAPE = parseGrid(`
##......
##......
##......
##......
##......
##......
######..
######..
`);

/** T-shape */
export const T_SHAPE = parseGrid(`
########
########
...##...
...##...
...##...
...##...
...##...
...##...
`);

/** Plus/cross shape */
export const PLUS_SHAPE = parseGrid(`
...##...
...##...
########
########
########
########
...##...
...##...
`);

/** Circle-ish (diamond approximation on 8×8) */
export const CIRCLE_ISH = parseGrid(`
..####..
.######.
########
########
########
########
.######.
..####..
`);

/** Empty grid */
export const EMPTY = parseGrid(`
........
........
........
........
........
........
........
........
`);

/** Diagonal stripe (tricky for marching squares) */
export const DIAGONAL = parseGrid(`
#.......
##......
.##.....
..##....
...##...
....##..
.....##.
......##
`);

/** Two disconnected squares */
export const TWO_SQUARES = parseGrid(`
##....##
##....##
........
........
........
........
##....##
##....##
`);

/** Hollow square (ring) */
export const HOLLOW_SQUARE = parseGrid(`
########
#......#
#......#
#......#
#......#
#......#
#......#
########
`);

/** Checkerboard (worst case for marching squares saddle points) */
export const CHECKERBOARD = parseGrid(`
#.#.#.#.
.#.#.#.#
#.#.#.#.
.#.#.#.#
#.#.#.#.
.#.#.#.#
#.#.#.#.
.#.#.#.#
`);
