name = "shape-research"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[durable_objects]
bindings = [
  { name = "SHAPE_REGISTRY", class_name = "ShapeRegistry" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ShapeRegistry"]

[[kv_namespaces]]
binding = "SHAPES"
id = "85b3a8b263c14f3992cb4ec99ed59479"
